"
" vim configuration file
"
" Must link or copy this file to ~/.vimrc
"
" Based on http://mislav.uniqpath.com/2011/12/vim-revisited/
"          https://github.com/mislav/vimfiles/blob/master/vimrc
"

"" Load Pathogen
call pathogen#infect()
call pathogen#helptags()

set nocompatible                " choose no compatibility with legacy vi
syntax enable

if has('gui_running')
    set background=light
    colorscheme solarized
else
    set background=dark
    colorscheme wombat 
endif


set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation
set number                      " Show line numbers
set mouse=a                     " Enable mouse to visual mode

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=4                   " a tab is 4 spaces
set shiftwidth=4                " an autoident is 4 spaces
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

