"
" vim configuration file
"
" Must link or copy this file to ~/.vimrc
"
" Based on http://mislav.uniqpath.com/2011/12/vim-revisited/
"          https://github.com/mislav/vimfiles/blob/master/vimrc
"          http://ftp.twaren.net/vim/runtime/mswin.vim
"
"

"" Load Pathogen
call pathogen#infect()
call pathogen#helptags()

set nocompatible                " choose no compatibility with legacy vi
syntax enable

if has('gui_running')
    set background=light
    colorscheme solarized
else
    set background=dark
    colorscheme wombat 
endif

"" Common options
set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation
set number                      " Show line numbers
set mouse=a                     " Enable mouse to visual mode

"" Highlight
set cursorline

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=4                   " a tab is 4 spaces
set shiftwidth=4                " an autoident is 4 spaces
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

"" friendly keyboard
" backspace in Visual mode deletes selection
vnoremap <BS> d

" CTRL-X and SHIFT-Del are Cut
vnoremap <C-X> "+x
vnoremap <S-Del> "+x

" CTRL-C and CTRL-Insert are Copy
vnoremap <C-C> "+y
vnoremap <C-Insert> "+y

" CTRL-V and SHIFT-Insert are Paste
map <C-V>		"+gP
map <S-Insert>		"+gP

cmap <C-V>		<C-R>+
cmap <S-Insert>		<C-R>+

" Pasting blockwise and linewise selections is not possible in Insert and
" Visual mode without the +virtualedit feature.  They are pasted as if they
" were characterwise instead.
" Uses the paste.vim autoload script.

exe 'inoremap <script> <C-V>' paste#paste_cmd['i']
exe 'vnoremap <script> <C-V>' paste#paste_cmd['v']

imap <S-Insert>		<C-V>
vmap <S-Insert>		<C-V>

" Use CTRL-Q to do what CTRL-V used to do
noremap <C-Q>		<C-V>

" Use CTRL-S for saving, also in Insert mode
noremap <C-S>		:update<CR>
vnoremap <C-S>		<C-C>:update<CR>
inoremap <C-S>		<C-O>:update<CR>

" For CTRL-V to work autoselect must be off.
" On Unix we have two selections, autoselect can be used.
if !has("unix")
  set guioptions-=a
endif

" CTRL-Z is Undo; not in cmdline though
noremap <C-Z> u
inoremap <C-Z> <C-O>u

" CTRL-Y is Redo (although not repeat); not in cmdline though
noremap <C-Y> <C-R>
inoremap <C-Y> <C-O><C-R>

" CTRL-A is Select all
noremap <C-A> gggH<C-O>G
inoremap <C-A> <C-O>gg<C-O>gH<C-O>G
cnoremap <C-A> <C-C>gggH<C-O>G
onoremap <C-A> <C-C>gggH<C-O>G
snoremap <C-A> <C-C>gggH<C-O>G
xnoremap <C-A> <C-C>ggVG

" CTRL-Tab is Next window
noremap <C-Tab> <C-W>w
inoremap <C-Tab> <C-O><C-W>w
cnoremap <C-Tab> <C-C><C-W>w
onoremap <C-Tab> <C-C><C-W>w

" CTRL-F4 is Close window
noremap <C-F4> <C-W>c
inoremap <C-F4> <C-O><C-W>c
cnoremap <C-F4> <C-C><C-W>c
onoremap <C-F4> <C-C><C-W>c

if has("gui_macvim")
    " Use command + 1, 2, 3... to navigate between tabs
    nmap <D-1> :tabn 1<CR>
    nmap <D-2> :tabn 2<CR>
    nmap <D-3> :tabn 3<CR>
    nmap <D-4> :tabn 4<CR>
    nmap <D-5> :tabn 5<CR>
    nmap <D-6> :tabn 6<CR>
    nmap <D-7> :tabn 7<CR>
    nmap <D-8> :tabn 8<CR>
    nmap <D-9> :tabn 9<CR>
    nmap <D-0> :tabn 10<CR>
endif

if has("gui_running")
    " Code completion using Ctrl+Space!
    inoremap <C-Space> <C-n>

    " Save session when we leave vim and open session when we get back
    fu! SaveSess()                                                                                                                                                                                                                                                                                                              
        execute 'mksession! ' . getcwd() . '/.session.vim'                                                                                                                                                                                                                                                                      
    endfunction                                                                                                                                                                                                                                                                                                                 

    fu! RestoreSess()                                                                                                                                                                                                                                                                                                           
        if filereadable(getcwd() . '/.session.vim')                                                                                                                                                                                                                                                                                 
            execute 'so ' . getcwd() . '/.session.vim'                                                                                                                                                                                                                                                                              
            if bufexists(1)                                                                                                                                                                                                                                                                                                         
                for l in range(1, bufnr('$'))                                                                                                                                                                                                                                                                                       
                    if bufwinnr(l) == -1                                                                                                                                                                                                                                                                                            
                        exec 'sbuffer ' . l                                                                                                                                                                                                                                                                                         
                    endif                                                                                                                                                                                                                                                                                                           
                endfor                                                                                                                                                                                                                                                                                                              
            endif                                                                                                                                                                                                                                                                                                                   
        endif                                                                                                                                                                                                                                                                                                                       
        syntax on                                                                                                                                                                                                                                                                                                                   
    endfunction                                                                                                                                                                                                                                                                                                                 

    autocmd VimLeave * call SaveSess()                                                                                                                                                                                                                                                                                          
    autocmd VimEnter * call RestoreSess()
endif
